---
apiVersion: v1
kind: Secret
metadata:
  name: library-service-secret
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: cGFzc3dvcmQK

# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: registry-secret
# type: Opaque
# data:
#   username: admin
#   password: "123456"