spring:
  datasource:
    url: jdbc:h2:mem:maindb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    platform: h2
  sql:
    init:
      mode: never
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
  shell:
    interactive:
      enabled: true
  flyway:
    enabled: true
    locations: classpath:db/migration,classpath:db/data
logging:
  logging:
    level:
      root: debug
  file:
    name: hw.log


