spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: maindb
  shell:
    interactive:
      enabled: true
    noninteractive:
      enabled: false
    command:
      version:
        enabled: false
#  main:
#    allow-bean-definition-overriding: true
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 5.0.5

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.hw.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

logging:
  level:
      root: debug
      org.springframework.boot.autoconfigure.mongo.embedded: error
  file:
    name: hw.log


