
spring:
  datasource:
    url: jdbc:h2:mem:maindb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    platform: h2
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
  shell:
    interactive:
      enabled: true
  flyway:
    enabled: true
    locations: classpath:db/migration,classpath:db/data
logging:
  logging:
    level:
      root: debug
  file:
    name: hw.log
