/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...page]': RouteRecordInfo<'/[...page]', '/:page(.*)', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/authors/': RouteRecordInfo<'/authors/', '/authors', Record<never, never>, Record<never, never>>,
    '/books/': RouteRecordInfo<'/books/', '/books', Record<never, never>, Record<never, never>>,
    '/books/[id]': RouteRecordInfo<'/books/[id]', '/books/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/books/create': RouteRecordInfo<'/books/create', '/books/create', Record<never, never>, Record<never, never>>,
    '/books/edit/[id]': RouteRecordInfo<'/books/edit/[id]', '/books/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/genres/': RouteRecordInfo<'/genres/', '/genres', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/[...page].vue': {
      routes: '/[...page]'
      views: never
    }
    'src/pages/authors/index.vue': {
      routes: '/authors/'
      views: never
    }
    'src/pages/books/index.vue': {
      routes: '/books/'
      views: never
    }
    'src/pages/books/[id].vue': {
      routes: '/books/[id]'
      views: never
    }
    'src/pages/books/create.vue': {
      routes: '/books/create'
      views: never
    }
    'src/pages/books/edit/[id].vue': {
      routes: '/books/edit/[id]'
      views: never
    }
    'src/pages/genres/index.vue': {
      routes: '/genres/'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
